version: "3.8"

services:
  app:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: futmatch
      POSTGRES_PASSWORD: 123123
      POSTGRES_DB: futmatch
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
    driver: local